import {createHash} from 'node:crypto';

import type {NormalizedNativeVariantsOptions} from '../options';

const GENERATED_START = '# @generated by expo-native-variants';
const GENERATED_END = '# @end generated by expo-native-variants';

type UpdatePodfileArgs = Readonly<{
  contents: string;
  projectName: string;
  options: NormalizedNativeVariantsOptions;
}>;

export function updatePodfile({contents, projectName, options}: UpdatePodfileArgs): string {
  const withoutGeneratedMapping = removeGeneratedMapping(contents);
  rejectForeignProjectMapping(withoutGeneratedMapping);

  const targetIndex = withoutGeneratedMapping.search(/^target\s+['"]/m);
  if (targetIndex < 0) {
    throw new Error(
      'expo-native-variants could not find the application target in the iOS Podfile.',
    );
  }

  const prefix = withoutGeneratedMapping.slice(0, targetIndex).trimEnd();
  const suffix = withoutGeneratedMapping.slice(targetIndex).trimStart();
  const mapping = createProjectMapping({projectName, options});

  return `${prefix}\n\n${mapping}\n\n${suffix}`;
}

function createProjectMapping({
  projectName,
  options,
}: Readonly<{
  projectName: string;
  options: NormalizedNativeVariantsOptions;
}>): string {
  const mappings = new Map<string, 'debug' | 'release'>([
    ['Debug', 'debug'],
    ['Release', 'release'],
  ]);

  for (const variant of options.variants) {
    mappings.set(variant.debugConfiguration, 'debug');
    mappings.set(variant.releaseConfiguration, 'release');
  }

  const entries = [...mappings]
    .map(([configuration, mode]) => `  '${escapeRuby(configuration)}' => :${mode}`)
    .join(',\n');

  const body = [
    `project '${escapeRuby(projectName)}', {`,
    entries,
    '}',
  ].join('\n');
  return [
    `${GENERATED_START} ${hashContent(body)}`,
    body,
    GENERATED_END,
  ].join('\n');
}

function removeGeneratedMapping(contents: string): string {
  const start = contents.indexOf(GENERATED_START);
  const end = contents.indexOf(GENERATED_END);

  if (start < 0 && end < 0) {
    return contents;
  }

  if (start < 0 || end < start) {
    throw new Error(
      'expo-native-variants found a malformed generated block in the iOS Podfile. Regenerate the native project before trying again.',
    );
  }

  const headerEnd = contents.indexOf('\n', start);
  if (headerEnd < 0 || headerEnd > end) {
    throw new Error(
      'expo-native-variants found a malformed generated block in the iOS Podfile. Regenerate the native project before trying again.',
    );
  }
  const header = contents.slice(start, headerEnd);
  const expectedHash = header.slice(GENERATED_START.length).trim();
  const body = contents.slice(headerEnd + 1, end).replace(/\n$/, '');
  if (!/^[a-f0-9]{16}$/.test(expectedHash) || hashContent(body) !== expectedHash) {
    throw new Error(
      'expo-native-variants will not replace its Podfile project mapping because the generated contents were modified.',
    );
  }

  return `${contents.slice(0, start)}${contents.slice(end + GENERATED_END.length)}`;
}

function rejectForeignProjectMapping(contents: string): void {
  if (/^\s*project\s+['"]/m.test(contents)) {
    throw new Error(
      'expo-native-variants cannot safely update a Podfile that already declares a CocoaPods project mapping.',
    );
  }
}

function escapeRuby(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
}

function hashContent(contents: string): string {
  return createHash('sha256').update(contents).digest('hex').slice(0, 16);
}
